// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    2: typeof import('./components/Main/Recommend/Friends.vue')['default']
    3: typeof import('./components/Main/Recommend/MV.vue')['default']
    AsideWidget: typeof import('./components/Aside/AsideWidget.vue')['default']
    copy: typeof import('./components/Main/Recommend/PersonalFM.vue')['default']
    Download: typeof import('./components/Main/Local/Download.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubmenu: typeof import('element-plus/es')['ElSubmenu']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FindMusic: typeof import('./components/Main/Recommend/FindMusic.vue')['default']
    FingMusic: typeof import('./components/Main/Recommend/FindMusic.vue')['default']
    Friends: typeof import('./components/Main/Recommend/Friends.vue')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpFullscreen: typeof import('~icons/ep/fullscreen')['default']
    IEpFullScreen: typeof import('~icons/ep/full-screen')['default']
    IEpMinus: typeof import('~icons/ep/minus')['default']
    LocalMusic: typeof import('./components/Main/Local/LocalMusic.vue')['default']
    MainWidget: typeof import('./components/MainWidget.vue')['default']
    MV: typeof import('./components/Main/Recommend/MV.vue')['default']
    PersonalFM: typeof import('./components/Main/Recommend/PersonalFM.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopWidget: typeof import('./components/Header/TopWidget.vue')['default']
    WindowToolBox: typeof import('./components/Header/WindowToolBox.vue')['default']
  }
}
